<?php
/**
 * Abilities API registration
 *
 * @package Lean_SEO
 * @since 1.0.0
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

class Lean_SEO_Abilities {

    /**
     * Register abilities.
     */
    public static function register() {
        wp_register_ability(
            'lean-seo/get-sitemap-urls',
            array(
                'label'               => __( 'Get Sitemap URLs', 'lean-seo' ),
                'description'         => __( 'Returns a list of sitemap URLs generated by Lean SEO.', 'lean-seo' ),
                'category'            => 'site',
                'execute_callback'    => array( __CLASS__, 'get_sitemap_urls' ),
                'permission_callback' => array( __CLASS__, 'can_view_sitemaps' ),
                'meta'                => array(
                    'annotations' => array(
                        'readonly'    => true,
                        'destructive' => false,
                        'idempotent'  => true,
                    ),
                ),
                'input_schema'        => array(
                    'type'                 => 'object',
                    'properties'           => array(),
                    'additionalProperties' => false,
                    // Hardening for the indirect-invocation path, which is
                    // stricter than direct invocation about a zero-arg call.
                    'default'              => (object) array(),
                ),
                'output_schema'       => array(
                    'type'  => 'array',
                    'items' => array(
                        'type' => 'string',
                    ),
                ),
            )
        );

        wp_register_ability(
            'lean-seo/get-post-seo',
            array(
                'label'               => __( 'Get Post SEO', 'lean-seo' ),
                'description'         => __( 'Returns SEO data for a specific post.', 'lean-seo' ),
                'category'            => 'site',
                'execute_callback'    => array( __CLASS__, 'get_post_seo' ),
                'permission_callback' => array( __CLASS__, 'can_edit_post' ),
                'meta'                => array(
                    'annotations' => array(
                        'readonly'    => true,
                        'destructive' => false,
                        'idempotent'  => true,
                    ),
                ),
                'input_schema'        => array(
                    'type'       => 'object',
                    'additionalProperties' => false,
                    'properties' => array(
                        'post_id' => array(
                            'type'        => 'integer',
                            'description' => __( 'Post ID to retrieve SEO data for.', 'lean-seo' ),
                        ),
                    ),
                    'required'   => array( 'post_id' ),
                ),
                'output_schema'       => array(
                    'type'       => 'object',
                    'properties' => array(
                        'post_id'     => array( 'type' => 'integer' ),
                        'title'       => array( 'type' => 'string' ),
                        'description' => array( 'type' => 'string' ),
                        'canonical'   => array( 'type' => 'string' ),
                        'custom'      => array(
                            'type'       => 'object',
                            'properties' => array(
                                'title'       => array( 'type' => 'string' ),
                                'description' => array( 'type' => 'string' ),
                            ),
                        ),
                    ),
                ),
            )
        );

        wp_register_ability(
            'lean-seo/audit-post-seo',
            array(
                'label'               => __( 'Audit Post SEO', 'lean-seo' ),
                'description'         => __( 'Analyzes a post for SEO issues and returns recommendations.', 'lean-seo' ),
                'category'            => 'site',
                'execute_callback'    => array( __CLASS__, 'audit_post_seo' ),
                'permission_callback' => array( __CLASS__, 'can_edit_post' ),
                'meta'                => array(
                    'annotations' => array(
                        'readonly'    => true,
                        'destructive' => false,
                        'idempotent'  => true,
                    ),
                ),
                'input_schema'        => array(
                    'type'       => 'object',
                    'additionalProperties' => false,
                    'properties' => array(
                        'post_id' => array(
                            'type'        => 'integer',
                            'description' => __( 'Post ID to audit.', 'lean-seo' ),
                        ),
                    ),
                    'required'   => array( 'post_id' ),
                ),
                'output_schema'       => array(
                    'type'       => 'object',
                    'properties' => array(
                        'post_id'      => array( 'type' => 'integer' ),
                        'title'        => array( 'type' => 'string' ),
                        'url'          => array( 'type' => 'string' ),
                        'score'        => array( 'type' => 'integer' ),
                        'issues'       => array( 
                            'type'  => 'array',
                            'items' => array(
                                'type'       => 'object',
                                'properties' => array(
                                    'type'     => array( 'type' => 'string' ),
                                    'severity' => array( 'type' => 'string' ),
                                    'message'  => array( 'type' => 'string' ),
                                    'value'    => array( 'type' => 'string' ),
                                ),
                            ),
                        ),
                        'stats'        => array(
                            'type'       => 'object',
                            'properties' => array(
                                'title_length'       => array( 'type' => 'integer' ),
                                'description_length' => array( 'type' => 'integer' ),
                                'word_count'         => array( 'type' => 'integer' ),
                                'h1_count'           => array( 'type' => 'integer' ),
                                'h2_count'           => array( 'type' => 'integer' ),
                                'internal_links'     => array( 'type' => 'integer' ),
                                'external_links'     => array( 'type' => 'integer' ),
                                'images'             => array( 'type' => 'integer' ),
                                'images_without_alt' => array( 'type' => 'integer' ),
                                'images_decorative'  => array( 'type' => 'integer' ),
                            ),
                        ),
                    ),
                ),
            )
        );

        wp_register_ability(
            'lean-seo/scan-seo-issues',
            array(
                'label'               => __( 'Scan SEO Issues', 'lean-seo' ),
                'description'         => __( 'Scans multiple posts for SEO issues and returns a summary.', 'lean-seo' ),
                'category'            => 'site',
                'execute_callback'    => array( __CLASS__, 'scan_seo_issues' ),
                'permission_callback' => array( __CLASS__, 'can_view_sitemaps' ),
                'meta'                => array(
                    'annotations' => array(
                        'readonly'    => true,
                        'destructive' => false,
                        'idempotent'  => true,
                    ),
                ),
                'input_schema'        => array(
                    'type'       => 'object',
                    'additionalProperties' => false,
                    'properties' => array(
                        'limit' => array(
                            'type'        => 'integer',
                            'description' => __( 'Maximum posts to scan (default: 50).', 'lean-seo' ),
                            'default'     => 50,
                        ),
                        'min_issues' => array(
                            'type'        => 'integer',
                            'description' => __( 'Minimum issues to include in results (default: 1).', 'lean-seo' ),
                            'default'     => 1,
                        ),
                        'post_type'  => array(
                            'type'        => 'string',
                            'description' => __( 'Post type to scan (default: post).', 'lean-seo' ),
                            'default'     => 'post',
                        ),
                    ),
                ),
                'output_schema'       => array(
                    'type'  => 'array',
                    'items' => array(
                        'type'       => 'object',
                        'properties' => array(
                            'post_id'     => array( 'type' => 'integer' ),
                            'title'       => array( 'type' => 'string' ),
                            'url'         => array( 'type' => 'string' ),
                            'score'       => array( 'type' => 'integer' ),
                            'issue_count' => array( 'type' => 'integer' ),
                            'top_issues'  => array( 'type' => 'array' ),
                        ),
                    ),
                ),
            )
        );

        wp_register_ability(
            'lean-seo/update-post-seo',
            array(
                'label'               => __( 'Update Post SEO', 'lean-seo' ),
                'description'         => __( 'Updates SEO meta for a specific post.', 'lean-seo' ),
                'category'            => 'site',
                'execute_callback'    => array( __CLASS__, 'update_post_seo' ),
                'permission_callback' => array( __CLASS__, 'can_edit_post' ),
                'meta'                => array(
                    'annotations' => array(
                        // Writes post meta, so not readonly. Not destructive:
                        // fields are updated, and an empty string clears one
                        // field rather than destroying a record. Idempotent:
                        // repeat calls with the same input write the same
                        // values with no accumulating effect.
                        'readonly'    => false,
                        'destructive' => false,
                        'idempotent'  => true,
                    ),
                ),
                'input_schema'        => array(
                    'type'       => 'object',
                    'additionalProperties' => false,
                    'properties' => array(
                        'post_id' => array(
                            'type'        => 'integer',
                            'description' => __( 'Post ID to update.', 'lean-seo' ),
                        ),
                        'title'   => array(
                            'type'        => 'string',
                            'description' => __( 'Custom SEO title. Empty string clears the value.', 'lean-seo' ),
                        ),
                        'description' => array(
                            'type'        => 'string',
                            'description' => __( 'Custom meta description. Empty string clears the value.', 'lean-seo' ),
                        ),
                    ),
                    'required'   => array( 'post_id' ),
                ),
                'output_schema'       => array(
                    'type'       => 'object',
                    'properties' => array(
                        'post_id'     => array( 'type' => 'integer' ),
                        'title'       => array( 'type' => 'string' ),
                        'description' => array( 'type' => 'string' ),
                        'canonical'   => array( 'type' => 'string' ),
                        'custom'      => array(
                            'type'       => 'object',
                            'properties' => array(
                                'title'       => array( 'type' => 'string' ),
                                'description' => array( 'type' => 'string' ),
                            ),
                        ),
                    ),
                ),
            )
        );
    }

    /**
     * Permission check for sitemap URLs.
     *
     * @return bool
     */
    public static function can_view_sitemaps() {
        return current_user_can( 'manage_options' );
    }

    /**
     * Permission check for post SEO abilities.
     *
     * @param array $input Ability input.
     * @return bool
     */
    public static function can_edit_post( $input ) {
        $post_id = isset( $input['post_id'] ) ? absint( $input['post_id'] ) : 0;
        if ( ! $post_id ) {
            return false;
        }

        return current_user_can( 'edit_post', $post_id );
    }

    /**
     * Return sitemap URLs.
     *
     * Asks the sitemap module rather than re-deriving its URL scheme. The
     * previous copy had drifted: it omitted custom post type sitemaps and
     * page pagination, so this ability contradicted the site's own
     * /sitemap.xml.
     *
     * @return array
     */
    public static function get_sitemap_urls() {
        $urls = array( home_url( '/sitemap.xml' ) );

        foreach ( Lean_SEO_Sitemap::get_sitemap_urls() as $entry ) {
            $urls[] = $entry['loc'];
        }

        return $urls;
    }

    /**
     * Return SEO data for a post.
     *
     * @param array $input Ability input.
     * @return array|WP_Error
     */
    public static function get_post_seo( $input ) {
        $post_id = isset( $input['post_id'] ) ? absint( $input['post_id'] ) : 0;
        if ( ! $post_id ) {
            return new WP_Error( 'lean_seo_invalid_post_id', __( 'Post ID is required.', 'lean-seo' ) );
        }

        $post = get_post( $post_id );
        if ( ! $post ) {
            return new WP_Error( 'lean_seo_invalid_post_id', __( 'No post exists with that ID.', 'lean-seo' ) );
        }

        $custom            = Lean_SEO_Post_Seo::all( $post );
        $custom_title       = $custom['title'];
        $custom_description = $custom['description'];
        $title              = $custom_title ? $custom_title : get_the_title( $post );
        $description        = $custom_description ? $custom_description : Lean_SEO_Description::generate( $post );

        return array(
            'post_id'     => $post_id,
            'title'       => $title,
            'description' => $description,
            'canonical'   => get_permalink( $post ),
            'custom'      => array(
                'title'       => $custom_title ? $custom_title : '',
                'description' => $custom_description ? $custom_description : '',
            ),
        );
    }

    /**
     * Update SEO data for a post.
     *
     * @param array $input Ability input.
     * @return array|WP_Error
     */
    public static function update_post_seo( $input ) {
        $post_id = isset( $input['post_id'] ) ? absint( $input['post_id'] ) : 0;
        if ( ! $post_id ) {
            return new WP_Error( 'lean_seo_invalid_post_id', __( 'Post ID is required.', 'lean-seo' ) );
        }

        $post = get_post( $post_id );
        if ( ! $post ) {
            return new WP_Error( 'lean_seo_invalid_post_id', __( 'No post exists with that ID.', 'lean-seo' ) );
        }

        $values = array();
        foreach ( array( 'title', 'description' ) as $field ) {
            if ( array_key_exists( $field, $input ) ) {
                $values[ $field ] = (string) $input[ $field ];
            }
        }

        Lean_SEO_Post_Seo::save( $post, $values );

        return self::get_post_seo( array( 'post_id' => $post_id ) );
    }

    /**
     * Audit a single post for SEO issues.
     *
     * @param array $input Ability input.
     * @return array|WP_Error
     */
    public static function audit_post_seo( $input ) {
        $post_id = isset( $input['post_id'] ) ? absint( $input['post_id'] ) : 0;
        if ( ! $post_id ) {
            return new WP_Error( 'lean_seo_invalid_post_id', __( 'Post ID is required.', 'lean-seo' ) );
        }

        $post = get_post( $post_id );
        if ( ! $post ) {
            return new WP_Error( 'lean_seo_invalid_post_id', __( 'No post exists with that ID.', 'lean-seo' ) );
        }

        return Lean_SEO_Audit::post( $post );
    }

    /**
     * Scan multiple posts for SEO issues.
     *
     * @param array $input Ability input.
     * @return array
     */
    public static function scan_seo_issues( $input ) {
        $limit      = isset( $input['limit'] ) ? absint( $input['limit'] ) : 50;
        $min_issues = isset( $input['min_issues'] ) ? absint( $input['min_issues'] ) : 1;
        $post_type  = isset( $input['post_type'] ) ? sanitize_key( $input['post_type'] ) : 'post';

        if ( ! post_type_exists( $post_type ) ) {
            return new WP_Error( 'lean_seo_invalid_post_type', __( 'That post type does not exist.', 'lean-seo' ) );
        }

        return Lean_SEO_Audit::scan( $limit, $min_issues, $post_type );
    }
}
