<?php
/**
 * Abilities API registration
 *
 * @package ThatSeoAgent
 * @since 1.0.0
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

class ThatSeoAgent_Abilities {

    /**
     * Register abilities.
     */
    public static function register() {
        wp_register_ability(
            'thatseoagent/get-sitemap-urls',
            array(
                'label'               => __( 'Get Sitemap URLs', 'thatseoagent' ),
                'description'         => __( 'Returns a list of sitemap URLs generated by ThatSeoAgent.', 'thatseoagent' ),
                'category'            => 'site',
                'execute_callback'    => array( __CLASS__, 'get_sitemap_urls' ),
                'permission_callback' => array( __CLASS__, 'can_view_sitemaps' ),
                'meta'                => array(
                    'annotations' => array(
                        'readonly'    => true,
                        'destructive' => false,
                        'idempotent'  => true,
                    ),
                ),
                'input_schema'        => array(
                    'type'                 => 'object',
                    'properties'           => array(),
                    'additionalProperties' => false,
                    // Hardening for the indirect-invocation path, which is
                    // stricter than direct invocation about a zero-arg call.
                    'default'              => (object) array(),
                ),
                'output_schema'       => array(
                    'type'  => 'array',
                    'items' => array(
                        'type' => 'string',
                    ),
                ),
            )
        );

        wp_register_ability(
            'thatseoagent/get-post-seo',
            array(
                'label'               => __( 'Get Post SEO', 'thatseoagent' ),
                'description'         => __( 'Returns SEO data for a specific post.', 'thatseoagent' ),
                'category'            => 'site',
                'execute_callback'    => array( __CLASS__, 'get_post_seo' ),
                'permission_callback' => array( __CLASS__, 'can_edit_post' ),
                'meta'                => array(
                    'annotations' => array(
                        'readonly'    => true,
                        'destructive' => false,
                        'idempotent'  => true,
                    ),
                ),
                'input_schema'        => array(
                    'type'       => 'object',
                    'additionalProperties' => false,
                    'properties' => array(
                        'post_id' => array(
                            'type'        => 'integer',
                            'description' => __( 'Post ID to retrieve SEO data for.', 'thatseoagent' ),
                        ),
                    ),
                    'required'   => array( 'post_id' ),
                ),
                'output_schema'       => array(
                    'type'       => 'object',
                    'properties' => array(
                        'post_id'     => array( 'type' => 'integer' ),
                        'title'       => array( 'type' => 'string' ),
                        'description' => array( 'type' => 'string' ),
                        'canonical'   => array( 'type' => 'string' ),
                        'noindex'     => array(
                            'type'        => 'boolean',
                            'description' => __( 'Whether the post is kept out of search results, the sitemap and llms.txt.', 'thatseoagent' ),
                        ),
                        'custom'      => array(
                            'type'       => 'object',
                            'properties' => array(
                                'title'       => array( 'type' => 'string' ),
                                'description' => array( 'type' => 'string' ),
                            ),
                        ),
                    ),
                ),
            )
        );

        wp_register_ability(
            'thatseoagent/audit-post-seo',
            array(
                'label'               => __( 'Audit Post SEO', 'thatseoagent' ),
                'description'         => __( 'Analyzes a post for SEO issues and returns recommendations. Only what Google or accessibility guidelines ask for lowers the score; findings of our own judgement are marked as such. Also returns the post\'s structure as facts — outline, lists, tables, figures, opening — for you to judge: no AI provider publishes how it chooses what to cite, so the plugin scores none of it. Read markdown_url for the full content.', 'thatseoagent' ),
                'category'            => 'site',
                'execute_callback'    => array( __CLASS__, 'audit_post_seo' ),
                'permission_callback' => array( __CLASS__, 'can_edit_post' ),
                'meta'                => array(
                    'annotations' => array(
                        'readonly'    => true,
                        'destructive' => false,
                        'idempotent'  => true,
                    ),
                ),
                'input_schema'        => array(
                    'type'       => 'object',
                    'additionalProperties' => false,
                    'properties' => array(
                        'post_id' => array(
                            'type'        => 'integer',
                            'description' => __( 'Post ID to audit.', 'thatseoagent' ),
                        ),
                    ),
                    'required'   => array( 'post_id' ),
                ),
                'output_schema'       => array(
                    'type'       => 'object',
                    'properties' => array(
                        'post_id'      => array( 'type' => 'integer' ),
                        'title'        => array( 'type' => 'string' ),
                        'url'          => array( 'type' => 'string' ),
                        'seo'          => array(
                            'type'        => 'object',
                            'description' => __( 'The title and description the page shows in search results, and whether the description was written or generated from the content.', 'thatseoagent' ),
                            'properties'  => array(
                                'title'               => array( 'type' => 'string' ),
                                'description'         => array( 'type' => 'string' ),
                                'description_written' => array( 'type' => 'boolean' ),
                            ),
                        ),
                        'score'        => array( 'type' => 'integer' ),
                        'issues'       => array( 
                            'type'  => 'array',
                            'items' => array(
                                'type'       => 'object',
                                'properties' => array(
                                    'type'     => array( 'type' => 'string' ),
                                    'severity' => array( 'type' => 'string' ),
                                    'source'   => array(
                                        'type'        => 'string',
                                        'enum'        => array( 'google', 'accessibility', 'heuristic' ),
                                        'description' => __( 'Who asks for it: Google Search Central, accessibility guidelines (WCAG 2.2), or our own judgement, which never lowers the score.', 'thatseoagent' ),
                                    ),
                                    'message'  => array( 'type' => 'string' ),
                                    'value'    => array( 'type' => 'string' ),
                                ),
                            ),
                        ),
                        'not_measured' => array(
                            'type'        => 'array',
                            'description' => __( 'Checks that could not run on this post, and why. A check that could not run is not a check that passed or failed.', 'thatseoagent' ),
                            'items'       => array(
                                'type'       => 'object',
                                'properties' => array(
                                    'type'    => array( 'type' => 'string' ),
                                    'message' => array( 'type' => 'string' ),
                                ),
                            ),
                        ),
                        'stats'        => array(
                            'type'       => 'object',
                            'properties' => array(
                                'title_length'       => array( 'type' => 'integer' ),
                                'description_length' => array( 'type' => 'integer' ),
                                'word_count'         => array( 'type' => 'integer' ),
                                'h1_count'           => array( 'type' => 'integer' ),
                                'h2_count'           => array( 'type' => 'integer' ),
                                'internal_links'     => array( 'type' => 'integer' ),
                                'external_links'     => array( 'type' => 'integer' ),
                                'uncrawlable_links'  => array( 'type' => 'integer' ),
                                'images'             => array( 'type' => 'integer' ),
                                'images_without_alt' => array( 'type' => 'integer' ),
                                'images_decorative'  => array( 'type' => 'integer' ),
                            ),
                        ),
                        'structure'    => array(
                            'type'        => 'object',
                            'description' => __( 'How the post is built, as facts with no verdict attached.', 'thatseoagent' ),
                            'properties'  => array(
                                'declared_language' => array(
                                    'type'        => 'string',
                                    'description' => __( 'The language the site declares in <html lang>, from Settings → General. Not detected from the text, which may be written in another.', 'thatseoagent' ),
                                ),
                                'published'    => array( 'type' => 'string' ),
                                'modified'     => array( 'type' => 'string' ),
                                'markdown_url' => array(
                                    'type'        => 'string',
                                    'description' => __( 'The post as Markdown, to read its full content. Empty when it has no Markdown version.', 'thatseoagent' ),
                                ),
                                'words'        => array( 'type' => 'integer' ),
                                'paragraphs'   => array( 'type' => 'integer' ),
                                'headings'     => array(
                                    'type'        => 'array',
                                    'description' => __( 'The content\'s headings in order, up to 60. The page title the theme prints is not among them.', 'thatseoagent' ),
                                    'items'       => array(
                                        'type'       => 'object',
                                        'properties' => array(
                                            'level' => array( 'type' => 'integer' ),
                                            'text'  => array( 'type' => 'string' ),
                                        ),
                                    ),
                                ),
                                'lists'        => array(
                                    'type'       => 'object',
                                    'properties' => array(
                                        'unordered' => array( 'type' => 'integer' ),
                                        'ordered'   => array( 'type' => 'integer' ),
                                        'items'     => array( 'type' => 'integer' ),
                                    ),
                                ),
                                'tables'       => array(
                                    'type'       => 'object',
                                    'properties' => array(
                                        'count' => array( 'type' => 'integer' ),
                                        'rows'  => array( 'type' => 'integer' ),
                                    ),
                                ),
                                'blockquotes'  => array( 'type' => 'integer' ),
                                'details'      => array(
                                    'type'        => 'integer',
                                    'description' => __( 'Details blocks: collapsible question-and-answer sections.', 'thatseoagent' ),
                                ),
                                'code_blocks'  => array( 'type' => 'integer' ),
                                'numbers'      => array(
                                    'type'        => 'integer',
                                    'description' => __( 'Figures in the text: every run of digits, years and prices included.', 'thatseoagent' ),
                                ),
                                'percentages'  => array( 'type' => 'integer' ),
                                'opening'      => array(
                                    'type'        => 'string',
                                    'description' => __( 'The first 150 words of the text, as a reader meets them.', 'thatseoagent' ),
                                ),
                            ),
                        ),
                    ),
                ),
            )
        );

        wp_register_ability(
            'thatseoagent/scan-seo-issues',
            array(
                'label'               => __( 'Scan SEO Issues', 'thatseoagent' ),
                'description'         => __( 'Scans multiple posts for SEO issues and returns a summary.', 'thatseoagent' ),
                'category'            => 'site',
                'execute_callback'    => array( __CLASS__, 'scan_seo_issues' ),
                'permission_callback' => array( __CLASS__, 'can_view_sitemaps' ),
                'meta'                => array(
                    'annotations' => array(
                        'readonly'    => true,
                        'destructive' => false,
                        'idempotent'  => true,
                    ),
                ),
                'input_schema'        => array(
                    'type'       => 'object',
                    'additionalProperties' => false,
                    'properties' => array(
                        'limit' => array(
                            'type'        => 'integer',
                            'description' => __( 'Maximum posts to scan (default: 50).', 'thatseoagent' ),
                            'default'     => 50,
                        ),
                        'min_issues' => array(
                            'type'        => 'integer',
                            'description' => __( 'Minimum issues to include in results (default: 1).', 'thatseoagent' ),
                            'default'     => 1,
                        ),
                        'post_type'  => array(
                            'type'        => 'string',
                            'description' => __( 'Post type to scan (default: post).', 'thatseoagent' ),
                            'default'     => 'post',
                        ),
                    ),
                ),
                'output_schema'       => array(
                    'type'  => 'array',
                    'items' => array(
                        'type'       => 'object',
                        'properties' => array(
                            'post_id'     => array( 'type' => 'integer' ),
                            'title'       => array( 'type' => 'string' ),
                            'url'         => array( 'type' => 'string' ),
                            'score'       => array( 'type' => 'integer' ),
                            'issue_count' => array( 'type' => 'integer' ),
                            'top_issues'  => array( 'type' => 'array' ),
                        ),
                    ),
                ),
            )
        );

        wp_register_ability(
            'thatseoagent/update-post-seo',
            array(
                'label'               => __( 'Update Post SEO', 'thatseoagent' ),
                'description'         => __( 'Updates SEO meta for a specific post.', 'thatseoagent' ),
                'category'            => 'site',
                'execute_callback'    => array( __CLASS__, 'update_post_seo' ),
                'permission_callback' => array( __CLASS__, 'can_edit_post' ),
                'meta'                => array(
                    'annotations' => array(
                        // Writes post meta, so not readonly. Not destructive:
                        // fields are updated, and an empty string clears one
                        // field rather than destroying a record. Idempotent:
                        // repeat calls with the same input write the same
                        // values with no accumulating effect.
                        'readonly'    => false,
                        'destructive' => false,
                        'idempotent'  => true,
                    ),
                ),
                'input_schema'        => array(
                    'type'       => 'object',
                    'additionalProperties' => false,
                    'properties' => array(
                        'post_id' => array(
                            'type'        => 'integer',
                            'description' => __( 'Post ID to update.', 'thatseoagent' ),
                        ),
                        'title'   => array(
                            'type'        => 'string',
                            'description' => __( 'Custom SEO title. Empty string clears the value.', 'thatseoagent' ),
                        ),
                        'description' => array(
                            'type'        => 'string',
                            'description' => __( 'Custom meta description. Empty string clears the value.', 'thatseoagent' ),
                        ),
                        'noindex' => array(
                            'type'        => 'boolean',
                            'description' => __( 'True keeps the post out of search results, the sitemap and llms.txt; false lets search engines index it again.', 'thatseoagent' ),
                        ),
                    ),
                    'required'   => array( 'post_id' ),
                ),
                'output_schema'       => array(
                    'type'       => 'object',
                    'properties' => array(
                        'post_id'     => array( 'type' => 'integer' ),
                        'title'       => array( 'type' => 'string' ),
                        'description' => array( 'type' => 'string' ),
                        'canonical'   => array( 'type' => 'string' ),
                        'noindex'     => array(
                            'type'        => 'boolean',
                            'description' => __( 'Whether the post is kept out of search results, the sitemap and llms.txt.', 'thatseoagent' ),
                        ),
                        'custom'      => array(
                            'type'       => 'object',
                            'properties' => array(
                                'title'       => array( 'type' => 'string' ),
                                'description' => array( 'type' => 'string' ),
                            ),
                        ),
                    ),
                ),
            )
        );
    }

    /**
     * Permission check for sitemap URLs.
     *
     * @return bool
     */
    public static function can_view_sitemaps() {
        return current_user_can( 'manage_options' );
    }

    /**
     * Permission check for post SEO abilities.
     *
     * @param array $input Ability input.
     * @return bool
     */
    public static function can_edit_post( $input ) {
        $post_id = isset( $input['post_id'] ) ? absint( $input['post_id'] ) : 0;
        if ( ! $post_id ) {
            return false;
        }

        return current_user_can( 'edit_post', $post_id );
    }

    /**
     * Return sitemap URLs.
     *
     * Asks the sitemap module rather than re-deriving its URL scheme. The
     * previous copy had drifted: it omitted custom post type sitemaps and
     * page pagination, so this ability contradicted the site's own
     * /sitemap.xml.
     *
     * @return array
     */
    public static function get_sitemap_urls() {
        $urls = array( home_url( '/sitemap.xml' ) );

        foreach ( ThatSeoAgent_Sitemap::get_sitemap_urls() as $entry ) {
            $urls[] = $entry['loc'];
        }

        return $urls;
    }

    /**
     * Return SEO data for a post.
     *
     * @param array $input Ability input.
     * @return array|WP_Error
     */
    public static function get_post_seo( $input ) {
        $post_id = isset( $input['post_id'] ) ? absint( $input['post_id'] ) : 0;
        if ( ! $post_id ) {
            return new WP_Error( 'thatseoagent_invalid_post_id', __( 'Post ID is required.', 'thatseoagent' ) );
        }

        $post = get_post( $post_id );
        if ( ! $post ) {
            return new WP_Error( 'thatseoagent_invalid_post_id', __( 'No post exists with that ID.', 'thatseoagent' ) );
        }

        $custom            = ThatSeoAgent_Post_Seo::all( $post );
        $custom_title       = $custom['title'];
        $custom_description = $custom['description'];
        $title              = ThatSeoAgent_Title::for_post( $post );
        $description        = ThatSeoAgent_Description::for_post( $post );

        return array(
            'post_id'     => $post_id,
            'title'       => $title,
            'description' => $description,
            'canonical'   => get_permalink( $post ),
            'noindex'     => ThatSeoAgent_Indexing::is_post_noindex( $post ),
            'custom'      => array(
                'title'       => $custom_title ? $custom_title : '',
                'description' => $custom_description ? $custom_description : '',
            ),
        );
    }

    /**
     * Update SEO data for a post.
     *
     * @param array $input Ability input.
     * @return array|WP_Error
     */
    public static function update_post_seo( $input ) {
        $post_id = isset( $input['post_id'] ) ? absint( $input['post_id'] ) : 0;
        if ( ! $post_id ) {
            return new WP_Error( 'thatseoagent_invalid_post_id', __( 'Post ID is required.', 'thatseoagent' ) );
        }

        $post = get_post( $post_id );
        if ( ! $post ) {
            return new WP_Error( 'thatseoagent_invalid_post_id', __( 'No post exists with that ID.', 'thatseoagent' ) );
        }

        $values = array();
        foreach ( array( 'title', 'description' ) as $field ) {
            if ( array_key_exists( $field, $input ) ) {
                $values[ $field ] = (string) $input[ $field ];
            }
        }

        if ( array_key_exists( 'noindex', $input ) ) {
            $values['noindex'] = $input['noindex'] ? '1' : '';
        }

        ThatSeoAgent_Post_Seo::save( $post, $values );

        return self::get_post_seo( array( 'post_id' => $post_id ) );
    }

    /**
     * Audit a single post for SEO issues.
     *
     * @param array $input Ability input.
     * @return array|WP_Error
     */
    public static function audit_post_seo( $input ) {
        $post_id = isset( $input['post_id'] ) ? absint( $input['post_id'] ) : 0;
        if ( ! $post_id ) {
            return new WP_Error( 'thatseoagent_invalid_post_id', __( 'Post ID is required.', 'thatseoagent' ) );
        }

        $post = get_post( $post_id );
        if ( ! $post ) {
            return new WP_Error( 'thatseoagent_invalid_post_id', __( 'No post exists with that ID.', 'thatseoagent' ) );
        }

        $audit = ThatSeoAgent_Audit::post( $post );

        // Facts for the agent to judge; the plugin draws no conclusion
        // from them. Not part of the content check on the screen, where
        // nobody reads them.
        $audit['structure'] = ThatSeoAgent_Structure::of( $post );

        return $audit;
    }

    /**
     * Scan multiple posts for SEO issues.
     *
     * @param array $input Ability input.
     * @return array
     */
    public static function scan_seo_issues( $input ) {
        $limit      = isset( $input['limit'] ) ? absint( $input['limit'] ) : 50;
        $min_issues = isset( $input['min_issues'] ) ? absint( $input['min_issues'] ) : 1;
        $post_type  = isset( $input['post_type'] ) ? sanitize_key( $input['post_type'] ) : 'post';

        if ( ! post_type_exists( $post_type ) ) {
            return new WP_Error( 'thatseoagent_invalid_post_type', __( 'That post type does not exist.', 'thatseoagent' ) );
        }

        return ThatSeoAgent_Audit::scan( $limit, $min_issues, $post_type );
    }
}
