<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInit0300bcfc6aad19f34e05505ca4d07bcd
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('ThatSeoAgent\Dependencies\Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \ThatSeoAgent\Dependencies\Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        require __DIR__ . '/platform_check.php';

        spl_autoload_register(array('ComposerAutoloaderInit0300bcfc6aad19f34e05505ca4d07bcd', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \ThatSeoAgent\Dependencies\Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInit0300bcfc6aad19f34e05505ca4d07bcd', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\ThatSeoAgent\Dependencies\Composer\Autoload\ComposerStaticInit0300bcfc6aad19f34e05505ca4d07bcd::getInitializer($loader));

        $loader->setClassMapAuthoritative(true);
        $loader->register(true);

        return $loader;
    }
}
