<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'ThatSeoAgent\\Dependencies\\League\\HTMLToMarkdown\\' => array($vendorDir . '/league/html-to-markdown/src'),
);
